import { createHash } from "node:crypto";

const YOUTUBE_ID = /^[A-Za-z0-9_-]{11}$/u;
const MAX_WATCH_BYTES = 6_000_000;
const MAX_CAPTION_BYTES = 8_000_000;
const MAX_TRANSCRIPT_CHARACTERS = 1_000_000;

export class YouTubeSourceError extends Error {
  readonly code: string;

  constructor(code: string) {
    super(code);
    this.code = code;
    this.name = "YouTubeSourceError";
  }
}

export type YouTubeLearningDocument = {
  externalId: string;
  title: string;
  body: string;
  language: string;
  mediaType: "text/plain";
  metadata: {
    provider: "youtube";
    videoId: string;
    videoUrl: string;
    authorName: string;
    captionLanguage: string;
    autoGenerated: boolean;
  };
};

export type YouTubeLearningSource = {
  videoId: string;
  videoUrl: string;
  title: string;
  authorName: string;
  contentHash: string;
  document: YouTubeLearningDocument;
};

type FetchLike = typeof fetch;

function boundedText(response: Response, maximumBytes: number) {
  const length = Number(response.headers.get("content-length") ?? "0");
  if (Number.isFinite(length) && length > maximumBytes) {
    throw new YouTubeSourceError("provider_response_too_large");
  }
  return response.text().then((body) => {
    if (Buffer.byteLength(body, "utf8") > maximumBytes) {
      throw new YouTubeSourceError("provider_response_too_large");
    }
    return body;
  });
}

function timedFetch(fetcher: FetchLike, url: string) {
  return fetcher(url, {
    signal: AbortSignal.timeout(12_000),
    headers: {
      "User-Agent": "LearningBot source importer/1.0",
      Accept: "application/json,text/html,application/xml,text/xml",
    },
  });
}

export function parseYouTubeVideoId(input: string) {
  const raw = input.trim();
  if (YOUTUBE_ID.test(raw)) return raw;

  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new YouTubeSourceError("invalid_youtube_url");
  }

  const hostname = url.hostname.toLowerCase().replace(/^www\./u, "");
  let candidate = "";
  if (hostname === "youtu.be") {
    candidate = url.pathname.split("/").filter(Boolean)[0] ?? "";
  } else if (
    hostname === "youtube.com" ||
    hostname === "m.youtube.com" ||
    hostname === "music.youtube.com"
  ) {
    if (url.pathname === "/watch") candidate = url.searchParams.get("v") ?? "";
    else {
      const [kind, value] = url.pathname.split("/").filter(Boolean);
      if (kind === "shorts" || kind === "embed" || kind === "live") {
        candidate = value ?? "";
      }
    }
  }

  if (!YOUTUBE_ID.test(candidate)) {
    throw new YouTubeSourceError("invalid_youtube_url");
  }
  return candidate;
}

function readBalancedJsonArray(source: string, marker: string) {
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) return null;
  const start = source.indexOf("[", markerIndex + marker.length);
  if (start < 0) return null;

  let depth = 0;
  let quoted = false;
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const character = source[index];
    if (quoted) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') quoted = false;
      continue;
    }
    if (character === '"') quoted = true;
    else if (character === "[") depth += 1;
    else if (character === "]") {
      depth -= 1;
      if (depth === 0) return source.slice(start, index + 1);
    }
  }
  return null;
}

type CaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string };
};

function chooseCaptionTrack(tracks: CaptionTrack[]) {
  const scored = tracks
    .filter((track) => typeof track.baseUrl === "string")
    .map((track) => ({
      track,
      score:
        (track.languageCode?.toLowerCase().startsWith("en") ? 4 : 0) +
        (track.kind === "asr" ? 0 : 2),
    }))
    .sort((left, right) => right.score - left.score);
  return scored[0]?.track ?? null;
}

function formatTimestamp(milliseconds: number) {
  const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  return hours > 0
    ? `[${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}]`
    : `[${minutes}:${String(seconds).padStart(2, "0")}]`;
}

function transcriptFromJson3(raw: string) {
  let payload: {
    events?: Array<{
      tStartMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };
  try {
    payload = JSON.parse(raw) as typeof payload;
  } catch {
    throw new YouTubeSourceError("captions_unavailable");
  }

  const lines: string[] = [];
  for (const event of payload.events ?? []) {
    const text = (event.segs ?? [])
      .map((segment) => segment.utf8 ?? "")
      .join("")
      .replace(/\s+/gu, " ")
      .trim();
    if (!text) continue;
    lines.push(`${formatTimestamp(event.tStartMs ?? 0)} ${text}`);
  }
  const transcript = lines.join("\n").trim();
  if (!transcript) throw new YouTubeSourceError("captions_unavailable");
  if (transcript.length > MAX_TRANSCRIPT_CHARACTERS) {
    throw new YouTubeSourceError("transcript_too_large");
  }
  return transcript;
}

export async function resolveYouTubeLearningSource(
  input: string,
  fetcher: FetchLike = fetch,
): Promise<YouTubeLearningSource> {
  const videoId = parseYouTubeVideoId(input);
  const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;

  const [metadataResponse, watchResponse] = await Promise.all([
    timedFetch(
      fetcher,
      `https://www.youtube.com/oembed?url=${encodeURIComponent(videoUrl)}&format=json`,
    ),
    timedFetch(fetcher, `${videoUrl}&hl=en&persist_hl=1`),
  ]);
  if (!metadataResponse.ok || !watchResponse.ok) {
    throw new YouTubeSourceError("youtube_video_unavailable");
  }

  const metadata = (await metadataResponse.json()) as {
    title?: unknown;
    author_name?: unknown;
  };
  const title =
    typeof metadata.title === "string" && metadata.title.trim()
      ? metadata.title.trim()
      : "YouTube video";
  const authorName =
    typeof metadata.author_name === "string" ? metadata.author_name.trim() : "";
  const watchPage = await boundedText(watchResponse, MAX_WATCH_BYTES);
  const encodedTracks = readBalancedJsonArray(watchPage, '"captionTracks":');
  if (!encodedTracks) throw new YouTubeSourceError("captions_unavailable");

  let tracks: CaptionTrack[];
  try {
    tracks = JSON.parse(encodedTracks) as CaptionTrack[];
  } catch {
    throw new YouTubeSourceError("captions_unavailable");
  }
  const track = chooseCaptionTrack(tracks);
  if (!track?.baseUrl) throw new YouTubeSourceError("captions_unavailable");

  let captionUrl: URL;
  try {
    captionUrl = new URL(track.baseUrl);
  } catch {
    throw new YouTubeSourceError("captions_unavailable");
  }
  if (
    captionUrl.protocol !== "https:" ||
    captionUrl.hostname !== "www.youtube.com" ||
    captionUrl.port !== "" ||
    captionUrl.username !== "" ||
    captionUrl.password !== "" ||
    captionUrl.pathname !== "/api/timedtext"
  ) {
    throw new YouTubeSourceError("captions_unavailable");
  }
  captionUrl.searchParams.set("fmt", "json3");
  const captionResponse = await timedFetch(fetcher, captionUrl.toString());
  if (!captionResponse.ok) {
    throw new YouTubeSourceError("captions_unavailable");
  }
  const transcript = transcriptFromJson3(
    await boundedText(captionResponse, MAX_CAPTION_BYTES),
  );
  const contentHash = createHash("sha256").update(transcript).digest("hex");
  const language = track.languageCode?.trim() || "und";

  return {
    videoId,
    videoUrl,
    title,
    authorName,
    contentHash,
    document: {
      externalId: videoId,
      title,
      body: transcript,
      language,
      mediaType: "text/plain",
      metadata: {
        provider: "youtube",
        videoId,
        videoUrl,
        authorName,
        captionLanguage: track.name?.simpleText?.trim() || language,
        autoGenerated: track.kind === "asr",
      },
    },
  };
}
