-- Admin-managed credentials and privacy-bounded product usage facts.
-- Temporary passwords are generated by the Auth control plane, returned once,
-- and never persisted in application tables.

begin;

create table app_private.user_access_accounts (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  tenant_id uuid not null references public.tenants(tenant_id),
  principal_id text not null references public.identity_principals(principal_id),
  membership_id text not null,
  email_normalized text not null
    check (
      email_normalized = lower(btrim(email_normalized))
      and length(email_normalized) between 3 and 320
    ),
  must_change_password boolean not null default true,
  credential_version bigint not null default 1 check (credential_version > 0),
  created_by_principal_id text references public.identity_principals(principal_id),
  password_changed_at timestamptz,
  last_signed_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (tenant_id, membership_id, principal_id)
    references public.identity_memberships(
      tenant_id, membership_id, principal_id
    ),
  unique (tenant_id, email_normalized),
  unique (auth_user_id, tenant_id, principal_id)
);
create index user_access_accounts_tenant_idx
  on app_private.user_access_accounts (tenant_id, created_at desc);

revoke all on table app_private.user_access_accounts
  from public, anon, authenticated;
grant select, insert, update on table app_private.user_access_accounts
  to service_role;

create table public.learning_usage_events (
  usage_event_id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(tenant_id),
  principal_id text not null references public.identity_principals(principal_id),
  membership_id text not null,
  identity_role text not null,
  event_name text not null check (event_name in (
    'auth.sign_in',
    'auth.password_changed',
    'account.provisioned',
    'learning.workspace_opened',
    'learning.course_started',
    'learning.course_completed',
    'learning.lesson_opened',
    'learning.lesson_completed',
    'conversation.started',
    'conversation.turn_completed',
    'learning.source_opened',
    'voice.session_started',
    'voice.session_ended',
    'voice.interrupted',
    'voice.reconnected',
    'voice.error',
    'upload.intent_created',
    'upload.quarantine_confirmed'
  )),
  properties jsonb not null default '{}'::jsonb
    check (jsonb_typeof(properties) = 'object'),
  idempotency_key text not null check (length(idempotency_key) between 8 and 200),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  retain_until timestamptz,
  record_version bigint not null default 1 check (record_version = 1),
  foreign key (tenant_id, membership_id, principal_id)
    references public.identity_memberships(
      tenant_id, membership_id, principal_id
    ),
  unique (tenant_id, idempotency_key),
  check (deleted_at is null)
);
create index learning_usage_events_tenant_time_idx
  on public.learning_usage_events (tenant_id, occurred_at desc);
create index learning_usage_events_name_time_idx
  on public.learning_usage_events (tenant_id, event_name, occurred_at desc);

create trigger learning_usage_events_reject_update
before update on public.learning_usage_events
for each row execute function app_private.reject_mutation();
create trigger learning_usage_events_reject_delete
before delete on public.learning_usage_events
for each row execute function app_private.reject_mutation();

alter table public.learning_usage_events enable row level security;
alter table public.learning_usage_events force row level security;

create policy learning_usage_events_admin_read
  on public.learning_usage_events
  for select to authenticated
  using (app_private.is_tenant_admin(tenant_id));

grant select on public.learning_usage_events to authenticated;
revoke insert, update, delete on public.learning_usage_events
  from public, anon, authenticated;

create or replace function app_private.access_account_context(
  target_auth_user_id uuid
)
returns table (
  auth_user_id uuid,
  tenant_id uuid,
  principal_id text,
  membership_id text,
  email_normalized text,
  identity_role text,
  must_change_password boolean,
  credential_version bigint
)
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select
    a.auth_user_id,
    a.tenant_id,
    a.principal_id,
    a.membership_id,
    a.email_normalized,
    m.role,
    a.must_change_password,
    a.credential_version
  from app_private.user_access_accounts a
  join public.identity_memberships m
    on m.tenant_id = a.tenant_id
   and m.membership_id = a.membership_id
   and m.principal_id = a.principal_id
  where a.auth_user_id = target_auth_user_id
    and m.status = 'active'
    and m.deleted_at is null;
$$;
revoke execute on function app_private.access_account_context(uuid)
  from public, anon, authenticated, service_role;

create or replace function public.auth_current_access_state()
returns table (
  managed boolean,
  must_change_password boolean,
  email_normalized text,
  identity_role text,
  credential_version bigint
)
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select
    true,
    c.must_change_password,
    c.email_normalized,
    c.identity_role,
    c.credential_version
  from app_private.access_account_context(auth.uid()) c
  union all
  select false, false, null::text, null::text, null::bigint
  where auth.uid() is not null
    and not exists (
      select 1
      from app_private.access_account_context(auth.uid())
    )
  limit 1;
$$;
revoke execute on function public.auth_current_access_state()
  from public, anon, service_role;
grant execute on function public.auth_current_access_state()
  to authenticated;

create or replace function public.auth_complete_password_change(
  requested_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  caller_id uuid := auth.uid();
  account app_private.user_access_accounts%rowtype;
begin
  if caller_id is null
    or requested_idempotency_key is null
    or length(requested_idempotency_key) not between 8 and 200
  then
    raise insufficient_privilege using message = 'Authenticated user required';
  end if;

  select a.* into account
  from app_private.user_access_accounts a
  where a.auth_user_id = caller_id
  for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'account_not_managed');
  end if;

  if account.must_change_password then
    update app_private.user_access_accounts
    set
      must_change_password = false,
      password_changed_at = clock_timestamp(),
      credential_version = credential_version + 1,
      updated_at = clock_timestamp()
    where auth_user_id = caller_id;

    insert into public.identity_audit_events (
      tenant_id, actor_principal_id, action, outcome, resource_type,
      resource_id, request_id, trace_id, safe_metadata, idempotency_key
    ) values (
      account.tenant_id,
      account.principal_id,
      'auth.password.change',
      'allowed',
      'auth_user',
      caller_id::text,
      requested_idempotency_key,
      requested_idempotency_key,
      jsonb_build_object('managedCredential', true),
      requested_idempotency_key
    )
    on conflict (tenant_id, idempotency_key) do nothing;
  end if;

  return jsonb_build_object(
    'ok', true,
    'mustChangePassword', false,
    'credentialVersion',
      account.credential_version + (account.must_change_password::integer)
  );
end;
$$;
revoke execute on function public.auth_complete_password_change(text)
  from public, anon, service_role;
grant execute on function public.auth_complete_password_change(text)
  to authenticated;

create or replace function public.learning_record_usage_event(
  requested_event_name text,
  requested_idempotency_key text,
  requested_properties jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  caller record;
  allowed_property_keys constant text[] := array[
    'courseId', 'lessonId', 'conversationId', 'modality', 'intent',
    'status', 'durationMs', 'sourceCount', 'errorCode', 'reconnectCount'
  ];
begin
  select * into caller from app_private.learning_rpc_context();
  if not found then
    return jsonb_build_object('ok', false, 'code', 'access_denied');
  end if;
  if requested_event_name not in (
    'auth.sign_in',
    'auth.password_changed',
    'account.provisioned',
    'learning.workspace_opened',
    'learning.course_started',
    'learning.course_completed',
    'learning.lesson_opened',
    'learning.lesson_completed',
    'conversation.started',
    'conversation.turn_completed',
    'learning.source_opened',
    'voice.session_started',
    'voice.session_ended',
    'voice.interrupted',
    'voice.reconnected',
    'voice.error',
    'upload.intent_created',
    'upload.quarantine_confirmed'
  )
    or requested_idempotency_key is null
    or length(requested_idempotency_key) not between 8 and 200
    or jsonb_typeof(coalesce(requested_properties, '{}'::jsonb)) <> 'object'
    or pg_column_size(coalesce(requested_properties, '{}'::jsonb)) > 4096
    or exists (
      select 1
      from jsonb_object_keys(coalesce(requested_properties, '{}'::jsonb)) k
      where k <> all(allowed_property_keys)
    )
  then
    return jsonb_build_object('ok', false, 'code', 'invalid_request');
  end if;

  insert into public.learning_usage_events (
    tenant_id, principal_id, membership_id, identity_role, event_name,
    properties, idempotency_key
  ) values (
    caller.tenant_id,
    caller.principal_id,
    caller.membership_id,
    caller.identity_role,
    requested_event_name,
    coalesce(requested_properties, '{}'::jsonb),
    requested_idempotency_key
  )
  on conflict (tenant_id, idempotency_key) do nothing;

  insert into public.telemetry_outbox (
    outbox_id, tenant_id, idempotency_key, topic, payload,
    payload_fingerprint, available_at
  ) values (
    'usage:' || requested_idempotency_key,
    caller.tenant_id,
    'usage:' || requested_idempotency_key,
    'learning.usage',
    jsonb_build_object(
      'eventName', requested_event_name,
      'properties', coalesce(requested_properties, '{}'::jsonb)
    ),
    encode(
      extensions.digest(
        convert_to(
          requested_event_name || ':' ||
          coalesce(requested_properties, '{}'::jsonb)::text,
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    ),
    clock_timestamp()
  )
  on conflict (tenant_id, idempotency_key) do nothing;

  return jsonb_build_object('ok', true, 'dataMode', 'durable');
end;
$$;
revoke execute on function public.learning_record_usage_event(
  text, text, jsonb
) from public, anon, service_role;
grant execute on function public.learning_record_usage_event(
  text, text, jsonb
) to authenticated;

create or replace function public.admin_list_access_accounts()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
declare
  caller record;
  accounts jsonb;
  usage jsonb;
begin
  select * into caller from app_private.learning_rpc_context();
  if not found
    or caller.identity_role not in ('tenant_owner', 'tenant_admin')
  then
    return jsonb_build_object('ok', false, 'code', 'access_denied');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'authUserId', a.auth_user_id,
    'email', a.email_normalized,
    'role', m.role,
    'status', m.status,
    'mustChangePassword', a.must_change_password,
    'createdAt', a.created_at,
    'passwordChangedAt', a.password_changed_at
  ) order by a.created_at), '[]'::jsonb)
  into accounts
  from app_private.user_access_accounts a
  join public.identity_memberships m
    on m.tenant_id = a.tenant_id
   and m.membership_id = a.membership_id
  where a.tenant_id = caller.tenant_id;

  select jsonb_build_object(
    'last30Days',
    coalesce((
      select jsonb_object_agg(event_name, event_count)
      from (
        select event_name, count(*)::bigint as event_count
        from public.learning_usage_events
        where tenant_id = caller.tenant_id
          and occurred_at >= clock_timestamp() - interval '30 days'
        group by event_name
      ) counts
    ), '{}'::jsonb),
    'activeLearners',
    coalesce((
      select count(distinct principal_id)
      from public.learning_usage_events
      where tenant_id = caller.tenant_id
        and occurred_at >= clock_timestamp() - interval '30 days'
        and (
          event_name like 'learning.%'
          or event_name like 'conversation.%'
          or event_name like 'voice.%'
        )
    ), 0)
  )
  into usage
  ;

  return jsonb_build_object(
    'ok', true,
    'dataMode', 'durable',
    'accounts', accounts,
    'usage', coalesce(usage, '{"last30Days":{},"activeLearners":0}'::jsonb)
  );
end;
$$;
revoke execute on function public.admin_list_access_accounts()
  from public, anon, service_role;
grant execute on function public.admin_list_access_accounts()
  to authenticated;

create or replace function public.admin_provision_auth_user(
  caller_auth_user_id uuid,
  target_auth_user_id uuid,
  target_email text,
  target_display_name text,
  target_identity_role text,
  requested_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  caller record;
  target_tenant_id uuid;
  target_principal_id text;
  target_membership_id text;
  legacy_role text;
  normalized_email text := lower(btrim(target_email));
begin
  if auth.role() <> 'service_role'
    or caller_auth_user_id is null
    or target_auth_user_id is null
    or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or length(btrim(coalesce(target_display_name, ''))) not between 1 and 160
    or target_identity_role not in (
      'tenant_owner', 'tenant_admin', 'creator', 'teacher', 'student'
    )
    or requested_idempotency_key is null
    or length(requested_idempotency_key) not between 8 and 200
  then
    return jsonb_build_object('ok', false, 'code', 'invalid_request');
  end if;

  select c.* into caller
  from app_private.supabase_auth_context_for_user(caller_auth_user_id) c;
  if not found
    or caller.identity_role not in ('tenant_owner', 'tenant_admin')
  then
    return jsonb_build_object('ok', false, 'code', 'access_denied');
  end if;
  if caller.identity_role = 'tenant_admin'
    and target_identity_role = 'tenant_owner'
  then
    return jsonb_build_object('ok', false, 'code', 'access_denied');
  end if;
  if not exists (
    select 1 from auth.users u
    where u.id = target_auth_user_id
      and lower(u.email) = normalized_email
      and u.deleted_at is null
      and u.email_confirmed_at is not null
  )
    or exists (
      select 1 from app_private.supabase_auth_principal_links l
      where l.auth_user_id = target_auth_user_id
    )
  then
    return jsonb_build_object('ok', false, 'code', 'auth_user_unavailable');
  end if;

  target_tenant_id := caller.tenant_id;
  target_principal_id := 'supabase-auth:' || target_auth_user_id::text;
  target_membership_id :=
    'supabase-auth-' || replace(target_identity_role, '_', '-') || ':' ||
    target_auth_user_id::text;
  legacy_role := case target_identity_role
    when 'tenant_owner' then 'owner'
    when 'tenant_admin' then 'client_admin'
    when 'creator' then 'client_viewer'
    when 'teacher' then 'client_viewer'
    else 'student'
  end;

  insert into public.identity_principals (
    principal_id, principal_kind, authentication_method, issuer, subject,
    idempotency_key
  ) values (
    target_principal_id, 'human', 'host_signed', 'supabase-auth',
    target_auth_user_id::text, requested_idempotency_key || ':principal'
  );
  insert into app_private.supabase_auth_principal_links (
    auth_user_id, principal_id, bootstrap_tenant_id, idempotency_key
  ) values (
    target_auth_user_id, target_principal_id, target_tenant_id,
    requested_idempotency_key || ':link'
  );
  insert into public.identity_memberships (
    membership_id, tenant_id, principal_id, role, status, provisioned_by,
    idempotency_key
  ) values (
    target_membership_id, target_tenant_id, target_principal_id,
    target_identity_role, 'active', 'manual',
    requested_idempotency_key || ':membership'
  );
  insert into public.profiles (
    tenant_id, user_id, display_name, metadata, idempotency_key
  ) values (
    target_tenant_id, target_auth_user_id, btrim(target_display_name),
    jsonb_build_object('managedAccess', true),
    requested_idempotency_key || ':profile'
  );
  insert into public.memberships (
    tenant_id, user_id, role_key, status, granted_by, idempotency_key
  ) values (
    target_tenant_id, target_auth_user_id, legacy_role, 'active',
    caller_auth_user_id, requested_idempotency_key || ':legacy-membership'
  );
  insert into app_private.supabase_auth_tenant_selections (
    auth_user_id, principal_id, tenant_id, membership_id
  ) values (
    target_auth_user_id, target_principal_id, target_tenant_id,
    target_membership_id
  );
  insert into app_private.user_access_accounts (
    auth_user_id, tenant_id, principal_id, membership_id, email_normalized,
    must_change_password, created_by_principal_id
  ) values (
    target_auth_user_id, target_tenant_id, target_principal_id,
    target_membership_id, normalized_email, true, caller.principal_id
  );
  insert into public.identity_audit_events (
    tenant_id, actor_principal_id, action, outcome, resource_type,
    resource_id, request_id, trace_id, safe_metadata, idempotency_key
  ) values (
    target_tenant_id, caller.principal_id, 'auth.account.provision',
    'allowed', 'auth_user', target_auth_user_id::text,
    requested_idempotency_key, requested_idempotency_key,
    jsonb_build_object('role', target_identity_role),
    requested_idempotency_key
  );

  return jsonb_build_object(
    'ok', true,
    'authUserId', target_auth_user_id,
    'tenantId', target_tenant_id,
    'role', target_identity_role,
    'mustChangePassword', true
  );
end;
$$;
revoke execute on function public.admin_provision_auth_user(
  uuid, uuid, text, text, text, text
) from public, anon, authenticated;
grant execute on function public.admin_provision_auth_user(
  uuid, uuid, text, text, text, text
) to service_role;

create or replace function public.admin_register_claimed_owner_access(
  target_auth_user_id uuid,
  target_email text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  context record;
  normalized_email text := lower(btrim(target_email));
begin
  if auth.role() <> 'service_role'
    or target_auth_user_id is null
    or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
  then
    return jsonb_build_object('ok', false, 'code', 'invalid_request');
  end if;
  select c.* into context
  from app_private.supabase_auth_context_for_user(target_auth_user_id) c;
  if not found or context.identity_role <> 'tenant_owner' then
    return jsonb_build_object('ok', false, 'code', 'access_denied');
  end if;

  insert into app_private.user_access_accounts (
    auth_user_id, tenant_id, principal_id, membership_id, email_normalized,
    must_change_password, created_by_principal_id
  ) values (
    target_auth_user_id, context.tenant_id, context.principal_id,
    context.membership_id, normalized_email, true, context.principal_id
  )
  on conflict (auth_user_id) do nothing;

  return jsonb_build_object(
    'ok', true,
    'tenantId', context.tenant_id,
    'mustChangePassword', true
  );
end;
$$;
revoke execute on function public.admin_register_claimed_owner_access(
  uuid, text
) from public, anon, authenticated;
grant execute on function public.admin_register_claimed_owner_access(
  uuid, text
) to service_role;

commit;
