import { NextResponse } from "next/server";
import {
  answerGroundedLearningQuestion,
  LearningProviderError,
  type GroundingSource,
} from "../../../../lib/learning-provider";
import {
  AuthenticationBoundaryError,
  assertSameOrigin,
  classifyAuthBoundaryError,
  getCurrentTenantContext,
  requireVerifiedUser,
} from "../../../../lib/supabase/auth-boundary";
import { AgentRpcError } from "../../../../lib/supabase/agent-rpc";
import { authenticatedLearningClient } from "../../../../lib/supabase/learning-route";
import { searchPublishedLearning } from "../../../../lib/semantic-learning-search";

/*
 * Runs one real, grounded turn against a DRAFT agent configuration in an
 * isolated session (PLAN.md Section 6.3): nothing here is persisted as a
 * conversation, no learning_conversations row is created, and no audit entry
 * is written — a preview is a read, not a change.
 *
 * The decision to refuse on empty retrieval is made here in code, not by a
 * creator-supplied flag: there is no field in the request body that can turn
 * it off. Only the WORDING of that refusal (noResultsMessage) comes from the
 * caller. When retrieval does return usable sources, the turn is generated by
 * the same src/lib/learning-provider.ts the live answer path uses, so the
 * platform base instruction and the <tenant_persona> untrusted-input boundary
 * are identical to what a real student would get — this route does not, and
 * cannot, construct its own prompt.
 */

const adminRoles = new Set(["tenant_owner", "tenant_admin"]);
const safeCodes = new Set([
  "access_denied",
  "invalid_request",
  "provider_not_configured",
  "provider_failed",
  "request_denied",
  "tenant_selection_required",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function stringValue(value: unknown) {
  return typeof value === "string" ? value : null;
}

function errorResponse(error: unknown) {
  if (error instanceof AuthenticationBoundaryError) {
    const failure = classifyAuthBoundaryError(error);
    return NextResponse.json(
      { ok: false, code: failure.code },
      { status: failure.status, headers: { "Cache-Control": "no-store" } },
    );
  }
  if (error instanceof LearningProviderError) {
    return NextResponse.json(
      { ok: false, code: error.code },
      { status: 503, headers: { "Cache-Control": "no-store" } },
    );
  }
  const code =
    error instanceof AgentRpcError && safeCodes.has(error.code)
      ? error.code
      : "request_denied";
  const status =
    code === "access_denied"
      ? 403
      : code === "tenant_selection_required"
        ? 409
        : code === "provider_not_configured" || code === "provider_failed"
          ? 503
          : 400;
  return NextResponse.json(
    { ok: false, code },
    { status, headers: { "Cache-Control": "no-store" } },
  );
}

function toGroundingSources(
  searchResult: unknown,
  similarityFloor: number,
): GroundingSource[] {
  if (!isRecord(searchResult) || !Array.isArray(searchResult.matches)) {
    return [];
  }
  return searchResult.matches.flatMap((candidate) => {
    if (!isRecord(candidate)) return [];
    // A degraded lexical match carries no semanticSimilarity at all; the
    // floor can only be applied when the retrieval actually scored one.
    const similarity =
      typeof candidate.semanticSimilarity === "number"
        ? candidate.semanticSimilarity
        : null;
    if (similarity !== null && similarity < similarityFloor) return [];
    const source = isRecord(candidate.source) ? candidate.source : {};
    const chunkId = stringValue(candidate.chunkId);
    const courseId = stringValue(candidate.courseId);
    const courseTitle = stringValue(candidate.courseTitle);
    const documentId = stringValue(candidate.documentId);
    const documentTitle = stringValue(candidate.documentTitle);
    const contentHash = stringValue(candidate.contentHash);
    const excerpt = stringValue(candidate.excerpt)?.replace(/<\/?b>/giu, "");
    if (
      !chunkId ||
      !courseId ||
      !courseTitle ||
      !documentId ||
      !documentTitle ||
      !contentHash ||
      !excerpt
    ) {
      return [];
    }
    return [
      {
        chunkId,
        courseId,
        courseTitle,
        documentId,
        documentTitle,
        contentHash,
        excerpt,
        lessonId: stringValue(source.lessonId),
        lessonTitle: stringValue(source.lessonName),
        sectionName: stringValue(source.sectionName),
      },
    ];
  });
}

export async function POST(request: Request) {
  try {
    assertSameOrigin(request);
    const supabase = await authenticatedLearningClient(request, {
      mutation: false,
    });
    const user = await requireVerifiedUser(supabase);
    const context = await getCurrentTenantContext(supabase);
    if (!context.selected || !context.tenantId) {
      throw new AgentRpcError("tenant_selection_required");
    }
    if (!context.identityRole || !adminRoles.has(context.identityRole)) {
      throw new AgentRpcError("access_denied");
    }

    const body = (await request.json()) as unknown;
    if (!isRecord(body)) throw new AgentRpcError("invalid_request");
    const question =
      typeof body.question === "string" ? body.question.trim() : "";
    if (question.length === 0 || question.length > 2000) {
      throw new AgentRpcError("invalid_request");
    }
    const assistantName =
      typeof body.assistantName === "string" &&
      body.assistantName.trim().length > 0
        ? body.assistantName.trim().slice(0, 80)
        : "Learning assistant";
    const tone =
      typeof body.tone === "string" ? body.tone.trim().toLowerCase() : null;
    const personaInstructions =
      typeof body.personaInstructions === "string"
        ? body.personaInstructions.trim().slice(0, 4000)
        : "";
    const extendedInstructions =
      typeof body.extendedInstructions === "string"
        ? body.extendedInstructions.trim().slice(0, 8000)
        : "";
    // Both are creator-authored guidance and receive the identical untrusted
    // handling inside answerGroundedLearningQuestion — this route does not
    // grant either one a different trust level.
    const combinedPersona =
      [personaInstructions, extendedInstructions]
        .filter((part) => part.length > 0)
        .join("\n\n") || null;
    const retrievalCount = Number.isFinite(Number(body.retrievalCount))
      ? Math.min(20, Math.max(1, Math.trunc(Number(body.retrievalCount))))
      : 6;
    const similarityFloor = Number.isFinite(Number(body.retrievalSimilarityFloor))
      ? Math.min(1, Math.max(0, Number(body.retrievalSimilarityFloor)))
      : 0.2;
    const noResultsMessage =
      typeof body.noResultsMessage === "string" &&
      body.noResultsMessage.trim().length > 0
        ? body.noResultsMessage.trim().slice(0, 500)
        : "I couldn't find this in the published learning yet. Try naming the course, lesson, or idea you want to understand.";
    const courseId =
      typeof body.courseId === "string" && body.courseId.trim().length > 0
        ? body.courseId.trim()
        : null;

    const requestId = `agent-preview:${crypto.randomUUID()}`;
    const traceId = `agent-preview:${crypto.randomUUID()}`;
    const idempotencyKey = `agent-preview:${crypto.randomUUID()}`;

    const searchResult = await searchPublishedLearning({
      request,
      supabase,
      query: question,
      courseId,
      limit: retrievalCount,
    });
    const sources = toGroundingSources(searchResult, similarityFloor);

    // The decision to refuse lives here, in code — never in a request field.
    if (sources.length === 0) {
      return NextResponse.json(
        {
          ok: true,
          dataMode: "ephemeral",
          preview: {
            refused: true,
            answer: noResultsMessage,
            sources: [],
            retrievalMode: stringValue(
              isRecord(searchResult) ? searchResult.retrievalMode : null,
            ),
          },
        },
        { headers: { "Cache-Control": "no-store" } },
      );
    }

    const answer = await answerGroundedLearningQuestion({
      assistantName,
      tenantId: context.tenantId,
      actorId: user.id,
      requestId,
      traceId,
      idempotencyKey,
      question,
      intent: "explain",
      scopeLabel: null,
      personaInstructions: combinedPersona,
      tone,
      history: [],
      sources,
    });

    return NextResponse.json(
      {
        ok: true,
        dataMode: "ephemeral",
        preview: {
          refused: false,
          answer: answer.answer,
          sources: sources.map((source) => ({
            chunkId: source.chunkId,
            courseTitle: source.courseTitle,
            documentTitle: source.documentTitle,
            lessonTitle: source.lessonTitle,
            excerpt: source.excerpt,
          })),
          model: answer.model,
          retrievalMode: stringValue(
            isRecord(searchResult) ? searchResult.retrievalMode : null,
          ),
        },
      },
      { headers: { "Cache-Control": "no-store" } },
    );
  } catch (error) {
    return errorResponse(error);
  }
}
